<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_58fde640ca723',
	'title' => 'About',
	'fields' => array (
		array (
			'key' => 'field_58fde66ca3b5f',
			'label' => 'About Section',
			'name' => 'about_section',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Location',
			'sub_fields' => array (
				array (
					'key' => 'field_58fde6a7a3b61',
					'label' => 'Location Name',
					'name' => 'about_location_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58fde68ca3b60',
					'label' => 'Header Image',
					'name' => 'about_header_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_58fde6e1a3b62',
					'label' => 'about_content',
					'name' => 'about_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array (
					'key' => 'field_58fde6f4a3b63',
					'label' => 'Email Button',
					'name' => 'about_email_button',
					'type' => 'email',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_58fde745a3b64',
					'label' => 'Information',
					'name' => 'about_information',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'br',
				),
				array (
					'key' => 'field_58fde7dea3b66',
					'label' => 'Pictures',
					'name' => 'about_pictures',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_58fde7ffa3b67',
							'label' => 'Picture',
							'name' => 'about_picture',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_58fde830a3b68',
							'label' => 'Size',
							'name' => 'about_picture_size',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'sm' => 'Small',
								'md' => 'Medium',
								'lg' => 'Large',
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '9',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58f750a79c790',
	'title' => 'Action Button',
	'fields' => array (
		array (
			'key' => 'field_58f75197eea31',
			'label' => 'Select type',
			'name' => 'content_action_button_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'none' => 'None',
				'url' => 'Custom URL',
				'post' => 'Link to post',
				'text' => 'Plain text',
			),
			'default_value' => array (
				0 => 'none',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58f750b98ff5c',
			'label' => 'URL',
			'name' => 'content_action_button_url',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58f75197eea31',
						'operator' => '==',
						'value' => 'url',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58f751e1eea32',
			'label' => 'Post',
			'name' => 'content_action_button_post',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58f75197eea31',
						'operator' => '==',
						'value' => 'post',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_58f75218eea33',
			'label' => 'Text',
			'name' => 'content_action_button_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58f75197eea31',
						'operator' => '==',
						'value' => 'text',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'topic',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'book',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58ec8eb08eff8',
	'title' => 'Block Size',
	'fields' => array (
		array (
			'key' => 'field_58ec8ebcc6cf6',
			'label' => 'Size',
			'name' => 'size',
			'type' => 'select',
			'instructions' => 'Select the size of the block. A \'Full width\' block will be full width on all screen sizes.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'xs' => 'Extra Small',
				'sm' => 'Small',
				'md' => 'Medium',
				'lg' => 'Large',
				'fw' => 'Full width',
			),
			'default_value' => array (
				0 => 'md',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58ec8f74c6cf7',
			'label' => 'Offset',
			'name' => 'offset',
			'type' => 'true_false',
			'instructions' => 'If you select this option this will offset the block, giving it a margin on the left side.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58ec8ebcc6cf6',
						'operator' => '!=',
						'value' => 'fw',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'book',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'sticky',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'topic',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58eb5ac786595',
	'title' => 'Block Type',
	'fields' => array (
		array (
			'key' => 'field_58eb5acb23db3',
			'label' => 'Type',
			'name' => 'type',
			'type' => 'select',
			'instructions' => 'Select the type of block that should be displayed on the page.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'text' => 'Text block',
				'colored_text' => 'Colored text block',
				'image' => 'Image block',
				'image_text' => 'Image block with text underneath',
			),
			'default_value' => array (
				0 => 'image_text',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58eb5c5e441b9',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'image',
					),
				),
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'image_text',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_58eb5c8a441bb',
			'label' => 'Caption',
			'name' => 'caption',
			'type' => 'textarea',
			'instructions' => 'This is the text that will be put on top of the image.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 2,
			'new_lines' => 'br',
		),
		array (
			'key' => 'field_58eb5ccb441bc',
			'label' => 'Position',
			'name' => 'caption_position',
			'type' => 'select',
			'instructions' => 'Position of the caption',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'top' => 'At the top of the image',
				'bottom' => 'At the bottom of the image',
			),
			'default_value' => array (
				0 => 'top',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58eb5d0f441bd',
			'label' => 'Color',
			'name' => 'caption_color',
			'type' => 'select',
			'instructions' => 'Text color',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'black' => 'Black',
				'white' => 'White',
			),
			'default_value' => array (
				0 => 'black',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58eb5ddd50752',
			'label' => 'Text',
			'name' => 'text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'text',
					),
				),
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'image_text',
					),
				),
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'colored_text',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
		array (
			'key' => 'field_58eb5e68b99e9',
			'label' => 'Background color',
			'name' => 'background_color',
			'type' => 'select',
			'instructions' => 'Background color of the block',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'colored_text',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'green' => 'Dark green',
				'yellow' => 'Bright yellow',
			),
			'default_value' => array (
				0 => 'yellow',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58ef66a6f0268',
			'label' => 'Action button',
			'name' => 'action_button',
			'type' => 'text',
			'instructions' => 'Highlighted red action button, leave empty to hide it.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'text',
					),
				),
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'image_text',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58ef6bb20f947',
			'label' => 'Link',
			'name' => 'link',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58eb5acb23db3',
						'operator' => '==',
						'value' => 'colored_text',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'book',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'sticky',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'topic',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58f717b9a2cb8',
	'title' => 'Custom block filler',
	'fields' => array (
		array (
			'key' => 'field_58f717d2f33e6',
			'label' => 'Custom Blocks',
			'name' => 'custom_blocks',
			'type' => 'repeater',
			'instructions' => 'Insert custom block content.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add block',
			'sub_fields' => array (
				array (
					'key' => 'field_58f71880f33e8',
					'label' => 'Size',
					'name' => 'custom_block_size',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'xs' => 'Extra Small',
						'sm' => 'Small',
						'md' => 'Medium',
						'lg' => 'Large',
						'fw' => 'Full width',
					),
					'default_value' => array (
						0 => 'md',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_58f718cbf33e9',
					'label' => 'Offset',
					'name' => 'custom_block_offset',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58f71880f33e8',
								'operator' => '==',
								'value' => 'xs',
							),
						),
						array (
							array (
								'field' => 'field_58f71880f33e8',
								'operator' => '==',
								'value' => 'sm',
							),
						),
						array (
							array (
								'field' => 'field_58f71880f33e8',
								'operator' => '==',
								'value' => 'md',
							),
						),
						array (
							array (
								'field' => 'field_58f71880f33e8',
								'operator' => '==',
								'value' => 'lg',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_58f71902f33ed',
					'label' => 'Type',
					'name' => 'custom_block_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'image' => 'Image',
						'image_text' => 'Image with text',
						'text' => 'Text only',
					),
					'default_value' => array (
						0 => 'image',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_58f7182af33e7',
					'label' => 'Image',
					'name' => 'custom_block_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58f71902f33ed',
								'operator' => '==',
								'value' => 'image',
							),
						),
						array (
							array (
								'field' => 'field_58f71902f33ed',
								'operator' => '==',
								'value' => 'image_text',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_58f7193ef33ee',
					'label' => 'Text',
					'name' => 'custom_block_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58f71902f33ed',
								'operator' => '==',
								'value' => 'image_text',
							),
						),
						array (
							array (
								'field' => 'field_58f71902f33ed',
								'operator' => '==',
								'value' => 'text',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 2,
					'new_lines' => 'br',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'topic',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'book',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58ef3538bde59',
	'title' => 'Front page header',
	'fields' => array (
		array (
			'key' => 'field_58ef355822a5d',
			'label' => 'Block Left',
			'name' => 'header_block',
			'type' => 'post_object',
			'instructions' => 'Select the post to be shown on top of the front page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'book',
				1 => 'topic',
				2 => 'sticky',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_59087d12bb32a',
			'label' => 'Size',
			'name' => 'header_block_size',
			'type' => 'select',
			'instructions' => 'Size of the left block',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'sm' => 'Small',
				'md' => 'Medium',
				'lg' => 'Large',
			),
			'default_value' => array (
				0 => 'md',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_59087d69bb32b',
			'label' => 'Block Right',
			'name' => 'header_block_right',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'book',
				1 => 'topic',
				2 => 'sticky',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_59087da4bb32c',
			'label' => 'Size',
			'name' => 'header_block_right_size',
			'type' => 'select',
			'instructions' => 'Size of the right block',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'sm' => 'Small',
				'md' => 'Medium',
				'lg' => 'Large',
			),
			'default_value' => array (
				0 => 'md',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58ef3c5e087e8',
	'title' => 'Header Image',
	'fields' => array (
		array (
			'key' => 'field_58ef3c6634765',
			'label' => 'Header Image',
			'name' => 'header_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'book',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'topic',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_590052bd5e426',
	'title' => 'Instagram Post',
	'fields' => array (
		array (
			'key' => 'field_59005307bd3f9',
			'label' => 'Instagram Shortcode',
			'name' => 'instagram_shortcode',
			'type' => 'text',
			'instructions' => 'Insert the shortcode for the post. <br>
Example: <strong>cdyP0</strong> is the shortcode from post https://www.instagram.com/p/cdyP0/',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'social_post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58ff6348eae8e',
	'title' => 'Social Feed',
	'fields' => array (
		array (
			'key' => 'field_58ff6353f69df',
			'label' => 'Instagram',
			'name' => 'instagram',
			'type' => 'text',
			'instructions' => 'Insert your Instagram access token, generate here: http://instagram.pixelunion.net/',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '16',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58f75112979c9',
	'title' => 'Details',
	'fields' => array (
		array (
			'key' => 'field_58f7512df7822',
			'label' => 'Details',
			'name' => 'content_details',
			'type' => 'textarea',
			'instructions' => 'Uppercase details, shown right after the title.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'topic',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'book',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_58ef4a0bcc338',
	'title' => 'Page block filler',
	'fields' => array (
		array (
			'key' => 'field_58ef4a8e940df',
			'label' => 'Page blocks',
			'name' => 'page_block_posts',
			'type' => 'repeater',
			'instructions' => 'Insert posts here to be shown on the front page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add block',
			'sub_fields' => array (
				array (
					'key' => 'field_58ef4b71940e0',
					'label' => 'Block',
					'name' => 'block',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'book',
						1 => 'sticky',
						2 => 'topic',
						3 => 'social_post',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
